package com.Temple.NutriBuddi.UserManagement.controller;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.Temple.NutriBuddi.UserManagement.model.User;
import com.Temple.NutriBuddi.UserManagement.repository.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/v1") // This means URL's start with /v1 (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

//	@Autowired
//    BeanFactory beanFactory;

	@GetMapping(path="/addNewUser") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String email
			, @RequestParam String password
			, @RequestParam String password2
			, @RequestParam String userName
			, @RequestParam String first
			, @RequestParam String last
			, @RequestParam String height
			, @RequestParam String weight
			, @RequestParam String age
			, @RequestParam String gender) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

//        User user = beanFactory.getBean(User.class);
        User user = new User();
		if (!email.equals("")) {
			if (userRepository.findByEmail(email) == null) {
				user.setEmail(email);
			} else {
				return "Email is already registered";
			}
		} else {
			return "Valid email required";
		}

		if (!password.equals("")) {
			if (password.equals(password2)) {
                user.setPassword(password);
			} else {
				return "Passwords must match";
			}
		} else {
			return "Password required";
		}

		if (!userName.equals("")) {
            user.setUserName(userName);
		} else {
			return "Username required";
		}

		if (!first.equals("")) {
            user.setFirstName(first);
		} else {
			return "First name required";
		}

		if (!last.equals("")) {
            user.setLastName(last);
		} else {
			return "Last name required";
		}

		if (!height.equals("")) {
            user.setHeight(Integer.parseInt(height));
		} else {
			return "Height required";
		}

		if (!weight.equals("")) {
            user.setWeight(Integer.parseInt(weight));
		} else {
			return "Weight required";
		}

		if (!age.equals("")) {
            user.setAge(Integer.parseInt(age));
		} else {
			return "Age required";
		}

		if (!gender.equals("")) {
            user.setGender(Integer.parseInt(gender));
		} else {
			return "Gender required";
		}
		
		userRepository.save(user);
		return "User added";
	}
	
	@GetMapping(path="/updateUser") // Map ONLY GET Requests
	public @ResponseBody String updateUser (@RequestParam String email
			, @RequestParam String password
			, @RequestParam String password2
			, @RequestParam String height
			, @RequestParam String weight
			, @RequestParam String age
			, @RequestParam String gender) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

        User user;


        if (!email.equals("")) {
			if (userRepository.findByEmail(email) != null) {
                user = userRepository.findByEmail(email);
			} else {
				return "Email does not exist";
			}
		} else {
			return "Valid email required";
		}

		if (!password.equals("")) {
			if (password.equals(password2)) {
                user.setPassword(password);
			} else {
				return "Passwords must match";
			}
		} else {
			return "Password required";
		}

		if (!height.equals("")) {
            user.setHeight(Integer.parseInt(height));
		} else {
			return "Height required";
		}

		if (!weight.equals("")) {
            user.setWeight(Integer.parseInt(weight));
		} else {
			return "Weight required";
		}

		if (!age.equals("")) {
            user.setAge(Integer.parseInt(age));
		} else {
			return "Age required";
		}

		if (!gender.equals("")) {
            user.setGender(Integer.parseInt(gender));
		} else {
			return "Gender required";
		}
		
		
		userRepository.save(user);
		return "Saved";
	}
	
	@GetMapping(path="/getUser") // Map ONLY GET Requests
	public @ResponseBody User getUser (@RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		return userRepository.findByEmail(email); 
	
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@GetMapping(path="/login")
	public @ResponseBody User userLogin(@RequestParam String email, @RequestParam String password) {
		
		return userRepository.findByEmailAndPassword(email, password);
	}
}